server:
  port: 8084

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/comment-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true