server:
  port: 8080

spring:
  application:
    name: service-discovery
  datasource:
    url: jdbc:postgresql://localhost:5432/user-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver